import { Component } from '@angular/core';

@Component({
  selector: 'app-line-dashboard',
  templateUrl: './line-dashboard.component.html',
  styleUrls: ['./line-dashboard.component.scss']
})
export class LineDashboardComponent {

    machineList = [
        { channel: 'Channel 1',
          machine: 'Machine 1',
          status: true,
          quality: true,
          vibration: true,
          health: true,
          alert: '21/34',
        },
        { channel: 'Channel 2',
          machine: 'Machine 2',
          status: true,
          quality: true,
          vibration: true,
          health: true,
          alert: 5,
        },
        { channel: 'Channel 3',
          machine: 'Machine 3',
          status: false,
          quality: true,
          vibration: true,
          health: true,
          alert: 23,
        },
        { channel: 'Channel 4',
          machine: 'Machine 4',
          status: true,
          quality: false,
          vibration: true,
          health: true,
          alert: 0,
        },
        { channel: 'Channel 5',
          machine: 'Machine 5',
          status: true,
          quality: true,
          vibration: true,
          health: true,
          alert: 23,
        },
        { channel: 'Channel 6',
          machine: 'Machine 6',
          status: false,
          quality: true,
          vibration: true,
          health: true,
          alert: 54,
        },
        { channel: 'Channel 7',
          machine: 'Machine 7',
          status: true,
          quality: false,
          vibration: true,
          health: true,
          alert: 0,
        },
        { channel: 'Channel 8',
          machine: 'Machine 8',
          status: false,
          quality: true,
          vibration: true,
          health: true,
          alert: 0,
        },
        { channel: 'Channel 9',
          machine: 'Machine 9',
          status: true,
          quality: true,
          vibration: true,
          health: true,
          alert: 0,
        },
        { channel: 'Channel 10',
          machine: 'Machine 10',
          status: false,
          quality: true,
          vibration: true,
          health: true,
          alert: 0,
        },
    ]

}
